version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=Pa55w0rd
  postgres:
      image: postgres
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: Pa55w0rd
volumes:
  postgres_data:
